### ISSUE TITLE
Issue in the Mobile / small devices view.

### ISSUE THREAD

**Issue by hs-07** [sugarlabs/www#399]
### Problem:
Unavailability of Hamburger Icon in Navbar.

### Issue:
 
When we open the [website](https://www.sugarlabs.org/), we cannot navigate through any **Navbar Hyperlinks** as they cant be assessed due to unavailability of **Hamburger Icon** in the Navbar. (as displayed below in picture)

![Screenshot_20230301_202223](https://user-images.githubusercontent.com/87127387/222176892-43b3243f-62ab-48ee-94af-56118bd18e57.png)

### Solution:
Enabling Hamburger Icon in Navbar and displaying all Hyperlinks appropriately.

### My efforts:
~ Had setup the site in local environment.
~ Started working over the this issue.

I would request the mentors or the developers to assign the issue to me for more clarity that no one else is not working on the same.
Thankyou.

**Comment by chimosky** [comment]
Thanks for pointing this out.

> I would request the mentors or the developers to assign the issue to me for more clarity that no one else is not working on the same.

We don't assign issues in our community but feel free to open a PR when you can, anyone is welcome to work on any issue and we can test each and pick the better solution or combine commits.

**Comment by quozl** [comment]
I've tested and reproduce the behaviour of no menu provided on small displays.  I've seen this before and didn't think it was a problem, because all the relevant links are at the bottom of the page, which is where a mobile user reaches once they have scrolled their small window over the content without tapping on anything.

A low priority issue.

I agree using a _hamburger_ is an appropriate thing to do.  However, the way it should be done is to make sure the content uses the existing feature, rather than adding any new coding.  This is because our aim should be to provide content for the web site rather than spend any significant time working on the style and layout.  Jekyll themes were chosen for this, and if they have been broken through ill-advised changes to the themes we should put them back the way they were, update them from upstream, or use a new theme.  Long term this strategy of _content first_ shall reduce wasted effort.

Would you like to get involved in the software that Sugar Labs actually produces, rather than looking at our web site?  Look at Sugarizer, Sugar activities, Music Blocks, or Turtle Blocks.

Also,

> I would request the mentors or the developers to assign the issue to me for more clarity that no one else is not working on the same.

This idea is a radical departure from our community norms.  If more than one person working on a problem is not acceptable to _you_, then this is not the sort of community _you_ should be contributing to.  Please look at the various ways in which humans organise themselves to achieve their goals, and then evaluate our community again.  Thanks!

**Comment by hs-07** [comment]
@chimosky @quozl 
Thank you for your valuable advices. 
@quozl Sir, surely I would like to get involved with the software Sugar Labs produces, infact I am looking into them too, but thought to get familiar with base code of Sugar Labs website and understand the workflow.

**Comment by quozl** [comment]
Okay, thanks.  That's an easy mistake to make.  The workflow in this repository is quite different to the workflow of our software.  Almost nothing is common between our web site and our software, except colours, and we've plans to change even that.
