### ISSUE TITLE
Error in installation steps mentioned in readme file

### ISSUE THREAD

**Issue by rockharshitmaurya** [sugarlabs/www#400]
There is a mistake in the installation steps mentioned in the readme file . The steps mention that the user should clone their forked copy of the project using the following command:

2. Clone your forked copy of the project.
```
git clone https://github.com/<your_user_name>/www-sugarlabs.git
```
3. Navigate to the project directory 📁.
```
cd www-sugarlabs
```

However, the name of the repository is www, not www-sugarlabs. Therefore, the correct command to navigate to the project directory should be:

2. Clone your forked copy of the project.
```
git clone https://github.com/<your_user_name>/www.git
```
3. Navigate to the project directory 📁.
```
cd www
```
This mistake can cause confusion for new contributors who are trying to set up the project for the first time. It would be great if the readme file could be updated to reflect this change in the installation steps.

if you find this an issue, I'll be happy to fix this.

Thank you.

**Comment by quozl** [comment]
Interesting.  This is because the repository was renamed.  GitHub keeps an alias of the old name, but a new fork won't hold the alias.

The README.md is also wrong by recommending clone by https instead of SSH.  The clone shell command should be removed in favour of a link to the GitHub help.

Please don't raise issues that you can just fix with a pull request.  Instead, make the pull request.

I've fixed this in 894008b ("Rename repository").
