### ISSUE TITLE
text color of "about us" option  and  "news" option

### ISSUE THREAD

**Issue by Ajaykumar724** [sugarlabs/www#545]
when i adjust width of website to smaller then 1215px , options text color is grey 
i also attach screenshot
![Screenshot 2024-11-10 182313](https://github.com/user-attachments/assets/0b2a3dee-2628-47fd-a3b0-380b1c6fa2e2)
but website width is greater than 1215px , options text color is blue
see below screenshot
![Screenshot 2024-11-10 182007](https://github.com/user-attachments/assets/1d9f3ad2-b349-4ef0-abfb-85e5ae915db2)
this is responsive error must be resolve that
thank you.

**Comment by therealharshit** [comment]
@Ajaykumar724 you can work on this, but make sure it didn't break the navbar.

**Comment by Ajaykumar724** [comment]
Ok @therealharshit 
I am greatful to contribute, you assign issue to me

**Comment by therealharshit** [comment]
> Ok @therealharshit 
> I am greatful to contribute, you assign issue to me 
> Thank you

We don't assign issues, you can raise a PR.

**Comment by Ajaykumar724** [comment]
Ok @therealharshit 
I am greatful to contribute, you assign issue to me

**Comment by Ajaykumar724** [comment]
@therealharshit I have small doubt b'coz I am beginner 
How to add dependencies on project

**Comment by therealharshit** [comment]
@Ajaykumar724 I think the dependencies are added as ruby gems. if you do `bundle install` it will install all the dependency you need to run this. 
I was wondering what dependencies you need to solve this issue?

**Comment by nilaygit-10721** [comment]
Is this issue still unresolved?

**Comment by therealharshit** [comment]
@nilaygit-10721 yes it's still unresolved. I think @nilaygit-10721 is working on this but you can also raise a PR.

**Comment by nilaygit-10721** [comment]
okay @therealharshit thank you

**Comment by Lakshya0257** [comment]
I have figured out the problem and solved the same, kindly review my PR for the same #550

**Comment by Sushant0124** [comment]
Is the issue resolved? If not Can i work on this??

**Comment by Sushant0124** [comment]
@therealharshit  I have understand the issue and to know where to do changes to resolve this but I am finding some issues in running the repo local

**Comment by therealharshit** [comment]
@Sushant0124 I suggest you to read https://github.com/sugarlabs/www/blob/master/README.md and for any further discussion you can join https://matrix.to/#/!OllliPClazQIIzhwoF:matrix.org?via=matrix.org

**Comment by quozl** [comment]
Thanks for getting involved.  Perhaps you all might keep discussion on issues on topic?  It has got difficult for a reviewer to figure out the consensus on this issue, because of all the off-topic posts.  I shall hide the off-topic posts.

I'd like the menu items to be foreground black regardless of screen size, but really that should be a decision of Bootstrap.  I'd like to know why it isn't working the way we expect; and speculate one or more of these causes;
* our code does not label elements correctly,
* our code includes something that breaks what Bootstrap does, or;
* the way we expect is wrong and Bootstrap is right.

**Comment by therealharshit** [comment]
@quozl it's not the decision of bootstap it's the `airspace.css` in which the style `.dropdown-menu li a{
  color: #0099ff !important;
}` is responsible for that blue color of dropdown menu, when we change the style to `.dropdown-menu li a{
  color:black !important;
}` it changes the color to black 
![dropdown](https://github.com/user-attachments/assets/59067a19-eb56-4862-8170-a04418770fed)
but for this we need to modify `airspace.css` which I think go against a long term goal of using a theme without changes.

**Comment by quozl** [comment]
So use custom.css, or go back to the upstream Jekyll Airspace theme on GItHub and remove our changes that broke this?  Is what we observe the upstream choice?

**Comment by srishti-jpg** [comment]
can anyone  tell me what's the problem ?

**Comment by aneesafatima** [comment]
Is this issue resolved?

**Comment by therealharshit** [comment]
> Is this issue resolved?
> 

Not yet, if you want you can work on it.

**Comment by aneesafatima** [comment]
May I ask why changing the airspace.css is not considered a solution? It we make it to black then it is no longer blue which solves this color issue.

**Comment by quozl** [comment]
I don't think this issue requires it, but also welcome is changing `airspace.css` so that it is less different to what it was upstream, at the same time as adding our changes to other files.

**Comment by yashsaraswat2004** [comment]
Hey, can I work on this issue?

**Comment by quozl** [comment]
Welcome.  Please join in.  But sorry, I don't understand.  Why can't you fix it without asking?  You are asking for the right to be the only one to fix it?  We can't offer that right.  Anyone could fix it.

**Comment by quozl** [comment]
Dear @Ajaykumar724 
(issue presenter), @nilaygit-10721 (asked if issue is unresolved) @Lakshya0257 (tried to solve with https://github.com/sugarlabs/www/pull/550), @Sushant0124 (asked if the issue is unresolved), @krAtOsnana (tried to solve with https://github.com/sugarlabs/www/pull/552), @aneesafatima (asked if the issue is unresolved), @yashsaraswat2004 (asked to work on the issue),

Please review https://github.com/sugarlabs/www/pull/565

Not sure how to review?  See our guide for reviewers; https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers

I was ready to merge, but found the issue has a large number of participants, so would like to ensure you all have a say in the review process.  Thanks!

**Comment by ad1tyayadav** [comment]
Hello @quozl can you please check my PR too :)
https://github.com/ad1tyayadav/www/commit/59c513540151c1c0ea8ba16057b6a2f51216cf39

**Comment by quozl** [comment]
Thanks @ad1tyayadav, I've reviewed it.  I think you misplaced your effort; for this issue it would have been better for you to review https://github.com/sugarlabs/www/pull/565 rather than try to fix the problem in another way.

I've given a chance for you all to review https://github.com/sugarlabs/www/pull/565 and there was no reply; this signals that either none of you were available or that none of you were willing to review.  Please get involved next time.

I'll proceed with finalising https://github.com/sugarlabs/www/pull/565.
